num_steps: 50

Grid:
    width: 100
    height: 100

#ModelConfig:
    #mode: CLASSIC
    #num_steps: 50
    #model_output_file: model.csv
    #graph_output_file: graph.%r.csv

#LoadBalancing:
    #enable: true
    #period: 20

Breakpoint:
    load_from: ""
    enable: false
    file: breakpoint.%r.bin
    start: 0
    period: 10

Prey:
    count: 50
    initial_energy: 4
    move_cost: 1
    energy_gain: 4
    reproduction_rate: 0.05

Predator:
    count: 20
    initial_energy: 20
    move_cost: 1
    energy_gain: 20
    reproduction_rate: 0.04

Grass:
    init_rate: 0.5
    growing_rate: 8
