num_steps: 50
sync_mode: GHOST_MODE
lb_output: false

Grid:
    width: 100
    height: 100

Prey:
    count: 250
    initial_energy: 4
    move_cost: 1
    energy_gain: 4
    reproduction_rate: 0.05
    mobility_range_size: 1

Predator:
    count: 170
    initial_energy: 20
    move_cost: 1
    energy_gain: 20
    reproduction_rate: 0.04
    perception_range_size: 1
    mobility_range_size: 1

Grass:
    init_rate: 0.5
    growing_rate: 8
